# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0002_remove_recipe_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
