# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0003_auto_20190305_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['recipe']},
        ),
    ]
