# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0003_auto_20190304_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
