# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0003_auto_20190316_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
