# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0004_delete_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('quantity', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.ManyToManyField(to='yumyum.Type'),
        ),
    ]
