# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0004_auto_20190305_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(blank=True, upload_to='recipe_images'),
        ),
    ]
