# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0005_auto_20190316_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set([('recipe', 'ingredient')]),
        ),
    ]
