# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0006_auto_20190304_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(choices=[(1, '1'), (2, '1'), (3, '1'), (4, '4'), (5, '5'), (6, '6')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '1'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
