# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0003_auto_20190318_2117'),
        ('yumyum', '0007_auto_20190317_1708'),
    ]

    operations = [
    ]
