# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import yumyum.models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0008_merge_20190318_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], validators=[yumyum.models.Recipe.number_positive_validator]),
        ),
    ]
