# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0008_auto_20190305_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='type',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('tsp.', 'tsp.'), ('tbsp.', 'tbsp.'), ('ml', 'ml'), ('l', 'l'), ('g', 'g'), ('kg', 'kg'), ('pieces', 'pieces'), ('pinch', 'pinch'), ('cloves', 'cloves'), ('slices', 'slices')], max_length=30),
        ),
    ]
