# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0008_auto_20190304_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
    ]
