# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import yumyum.models


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0009_auto_20190318_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[yumyum.models.Review.sensible_rating_validator]),
        ),
    ]
