# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yumyum', '0010_auto_20190306_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['type', 'name']},
        ),
    ]
